### ISSUE TITLE
TYPO3 9.5 Slug

### ISSUE THREAD

**Issue by infabo** [rupertgermann/tt_news#118]
tt_news does not create pretty URLs right now with TYPO3 9.5.

**Comment by Patta** [comment]
Maybe [routing enhancers](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.5/Feature-86365-RoutingEnhancersAndAspects.html) can help here? I didn't try it yet.

**Comment by Patta** [comment]
Here are examples for tt_news: https://typo3worx.eu/2018/12/typo3-routing-extensions-and-enhancers/

**Comment by Patta** [comment]
Here is my route enhancer for the detail view.
```
routeEnhancers:
    TtNewsDetail:
        type: Plugin
        limitToPages:
            - 23
            - 42
        namespace: 'tx_ttnews'
        routePath: '/{tt_news}'
        requirements:
            tt_news: '[0-9]{1..8}'
        aspects:
            tt_news:
                type: PersistedPatternMapper
                tableName: 'tt_news'
                routeFieldPattern: '^(?:.+)-(?P<uid>\d+)$'
                routeFieldResult: '{title}-{uid}'
```
But like discussed in this [core issue](https://forge.typo3.org/issues/86797), there is no sanitize in PersistedPatternMapper for the title field.
So a dedicated slug field is necessary.

**Comment by dklimpel** [comment]
In addition, here is my route enhancer for pagination.
```
  TtNewsPagination:
    type: Plugin
    namespace: 'tx_ttnews'
    routePath: '/browse/{pointer}'
    defaults:
      pointer: '0'
    requirements:
      pointer: '[0-9]{1..3}'
    aspects:
      pointer:
        type: StaticRangeMapper
        start: '1'
        end: '100'
```
