### ISSUE TITLE
routing enhancers url rewrite without uid

### ISSUE THREAD

**Issue by christiana83** [rupertgermann/tt_news#133]
Is there a possibility to make urls without uid by using routing enhancers? It's really necessary that we keep the old URLs after updating to TYPO3 9. The old URLs have been configured with RealUrl. Example: domain.de/detailview/article/articlename.html 
With routing enhancers news are only shown when the URL contains the uid 
Example: domain.de/detailview/article/articlename-12
I would be very happy about help!

**Comment by Patta** [comment]
#118

**Comment by christiana83** [comment]
Solved it by using PersitantPatternMappern and an own alias field for the news that should be unique:

```
routeEnhancers:
  TtNewsDetail:
    type: Plugin
    namespace: tx_ttnews
    routePath: '/artikel/{tt_news}'
    requirements:
      tt_news: '[0-9]{1..8}'
    aspects:
      tt_news:
        type: PersistedPatternMapper
        tableName: tt_news
        routeFieldPattern: '^(?P<pdp_ttnews_alias>.+)'
        routeFieldResult: '{pdp_ttnews_alias}'
```
